-- Generated by HyprMod

-- Settings
hl.config({
    animations = {
        enabled = true,
    },
    decoration = {
        blur = {
            enabled = true,
        },
        dim_inactive = false,
        rounding = 2,
    },
    ecosystem = {
        enforce_permissions = false,
        no_donation_nag = false,
        no_update_news = false,
    },
    general = {
        allow_tearing = true,
        gaps_out = 8,
        layout = "dwindle",
        snap = {
            enabled = false,
        },
    },
    misc = {
        disable_hyprland_logo = true,
    },
})

-- Animations
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10.0,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8.0,
    bezier = "default",
})

-- Monitors
hl.monitor({
    output = "DP-2",
    disabled = false,
    mode = "2560x1440@164.96Hz",
    position = "-840x-40",
    scale = 1,
    bitdepth = 10,
    cm = "hdr",
    sdrbrightness = 0.5,
    sdrsaturation = 1.4,
    sdr_min_luminance = 0.35,
    sdr_max_luminance = 351,
    min_luminance = 0.05,
    max_luminance = 351,
    max_avg_luminance = 351,
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@60.00Hz",
    position = "-1920x-270",
    scale = 1,
    transform = 1,
    cm = "srgb",
})

-- Keybinds
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("elecwhat"))
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("steam"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("vscodium"))

-- Window rules
hl.window_rule({
    match = {
        class = "^(fsel)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(wiremix)$",
    },
    float = true,
})
hl.window_rule({
    match = {
        class = "^(wiremix)$",
    },
    opacity = "1.00 1.00",
})
hl.window_rule({
    match = {
        class = "^(wiremix)$",
    },
    size = "1000 1000",
})
hl.window_rule({
    match = {
        class = "^(fsel)$",
    },
    opacity = "1.00 1.00",
})
hl.window_rule({
    match = {
        class = "^(fsel)$",
    },
    center = true,
})
hl.window_rule({
    match = {
        class = "^(wiremix)$",
    },
    move = "1500 50",
})
hl.window_rule({
    match = {
        class = "^(fsel)$",
    },
    size = "600 1000",
})
